version: '3.3'

services:

   db:
     container_name: tfs-db
     image: mysql:5.7
     networks:
       - tfs-network
     volumes:
       - ./running/database:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: forgottenserver
       MYSQL_USER: forgottenserver
       MYSQL_PASSWORD: forgottenserver

   server:
     container_name: tfs-server
     image: tfs
     networks:
       - tfs-network
     volumes:
       - ./running/server:/srv
     ports:
      - 7171:7171
      - 7172:7172

networks:
  tfs-network: {}